#!/usr/bin/env python3
import re
import subprocess
import sys
import argparse

ACTIONS = ['switch', 'status']
PRIMARY_OUT = 'eDP1'

###########################################
def run_xrandr(arg_list):
    '''run_xrandr(arg_list) -> ()

Runs xrandr with given string as arguments
'''
    return subprocess.getoutput('xrandr ' + ' '.join(arg_list))


###########################################
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Display switcher')
    parser.add_argument('action', metavar='action', choices=ACTIONS,
                        nargs='?', default='status',
                        help='action to be performed (one of {' +
                        ', '.join(ACTIONS) + '})')

    try:
        args = parser.parse_args()
    except Exception as ex:
        errprint(str(ex))

    xrandr_out = run_xrandr(['-d', ':0.0'])
    connected_lines = []
    for line in xrandr_out.split('\n'):
        if re.search(r'\bconnected', line):
            connected_lines.append(line)

    dev_connected = []
    for line in connected_lines:
        m = re.match(r'^\w+\b', line)
        dev_connected.append(m.group(0))

    dev_active = []
    for line in connected_lines:
        if re.search(r'\bconnected (primary )?[0-9]+', line):
            m = re.match(r'^\w+\b', line)
            dev_active.append(m.group(0))

    assert len(dev_connected) in {1, 2}

    secondary_out = ''
    if len(dev_connected) == 2:
        secondary_out = dev_connected - [PRIMARY_OUT]

    if args.action == 'switch':
        if len(dev_connected) == 1:
            run_xrandr(['--output HDMI2', '--off'])
            run_xrandr(['--output eDP1', '--auto'])
            sys.exit(0)

        if len(dev_active) == 2:
            run_xrandr(['--output eDP1', '--auto'])
            run_xrandr(['--output HDMI2', '--off'])
        elif dev_active == ['eDP1']:
            run_xrandr(['--output eDP1', '--off'])
            run_xrandr(['--output HDMI2', '--auto'])
        elif dev_active == ['HDMI2']:
            run_xrandr(['--output eDP1', '--auto'])
            run_xrandr(['--output HDMI2', '--right-of eDP1', '--auto'])
        else:
            assert False
    else:
        assert args.action == 'status'

        print(connected_lines)
        print('Connected devices:  ' + ' '.join(dev_connected))
        print('Active devices:     ' + ' '.join(dev_active))
        print('Primary output:     ' + PRIMARY_OUT)
        print('Secondary output:   ' + ('None' if not secondary_out else secondary_out))
