#!/usr/bin/env python3
import re
import subprocess
import sys
import argparse

ACTIONS = ['switch', 'status']
VERBOSE = 0

SCALING = {'3840x2160': '0.75'}

###########################################
class Device:
    '''Device

Represents an X device
'''
    ###########################################
    def __init__(self, name, status, primary, active):
        '''__init__(self, name, status, primary, active) -> cnstr

Constructor
'''
        self.name = name
        self.status = status
        self.primary = primary
        self.active = active
        self.resolutions = []
        self.current_res = None
        self.recommended_res = None

    ###########################################
    def __str__(self):
        '''__str__(self) -> string

Returns a string
    '''
        res = ''
        res += 'Name:        ' + self.name + '\n'
        res += 'Status:      ' + self.status + '\n'
        res += 'Primary:     ' + str(self.primary) + '\n'
        res += 'Active:      ' + str(self.active) + '\n'
        res += 'Resolutions: ' + ' '.join([w + 'x' + h for (w, h) in self.resolutions]) + '\n'
        res += 'Current res: ' + ('' if self.current_res is None else self.current_res[0] + 'x' + self.current_res[1]) + '\n'
        res += 'Recomm. res: ' + ('' if self.recommended_res is None else self.recommended_res[0] + 'x' + self.recommended_res[1]) + '\n'
        return res


###########################################
def run_xrandr(arg_list):
    '''run_xrandr(arg_list) -> string

Runs xrandr with given arguments and returns the output
'''
    command = 'xrandr ' + ' '.join(arg_list)
    if VERBOSE:
        print("log: running # " + command)

    return subprocess.getoutput(command)


###########################################
def run_xrandr_for(output, arg_list):
    '''run_xrandr_for(output, arg_list) -> ()

Runs xrandr for given output with given arguments and returns the output
'''
    return run_xrandr(['--output', output] + arg_list)


###########################################
def xrandr_turn_off(output):
    '''xrandr_turn_off(output) -> ()

Turns an output off.
'''
    run_xrandr_for(output, ['--off'])
    return


###########################################
def xrandr_turn_on(output, params=[]):
    '''xrandr_turn_off(output, params) -> ()

Turns an output on (additionally providing some parameters
'''
    additional_params = []
    scale = SCALING[output]
    if scale is not None:
        additional_params.append(['--scale', scale])

    run_xrandr_for(output, ['--auto'] + params + additional_params)
    return


###########################################
def parse_xrandr(xrandr_output):
    '''parse_xrandr(string) -> dict

Parses the output of XRandR
'''
    dev_dict = { }
    cur_dev = ''
    for line in xrandr_out.split('\n'):
        # PROCESSING SCREEN LINES
        if re.search(r'^Screen', line):
            continue        # skip 'Screen' lines

        # PROCESSING DEVICE LINES
        dev_re = re.compile(r'''
          ^                                              # > start of line
          (?P<name>\w+)\                                 # name of the device
          (?P<status>(dis)?connected)\                   # connected?
          (?P<primary>primary\ )?                        # primary output?
          (?P<size_off>[0-9]+x[0-9]+\+[0-9]+\+[0-9]+\ )? # size + offset
          ''', re.VERBOSE)
        m = dev_re.match(line)
        if m:
            # print('line: ' + line)
            dev = Device(name=m.group('name'),
                         status=m.group('status'),
                         primary=(m.group('primary') != None),
                         active=(m.group('size_off') != None))
            dev_dict[dev.name] = dev
            cur_dev = dev.name
            continue

        # PROCESSING RESOLUTION LINES
        res_re = re.compile(r'''
          ^\ +                                           # > start of line
          (?P<width>[0-9]+)                              # screen width
          x                                              # > separator
          (?P<height>[0-9]+)                             # screen height
          (?P<is_i>i)?                                   # the 'i' parameter
          \ +                                            # > separator
          (?P<refresh>[0-9\.]+)                          # refresh rate
          (?P<is_cur_res>\*)?                            # active setting
          (?P<is_rec_res>\+)?                            # recommended setting
          ''', re.VERBOSE)
        m = res_re.match(line)
        if m:
            if m.group('is_i') is None:
                resolution = (m.group('width'), m.group('height'))
                dev_dict[cur_dev].resolutions.append(resolution)
                if m.group('is_cur_res') is not None:
                    dev_dict[cur_dev].current_res = resolution
                if m.group('is_rec_res') is not None:
                    dev_dict[cur_dev].recommended_res = resolution
            continue

        print('failing: ' + line)
        # shouldn't get here
        assert False

    for dev in dev_dict.values():
        print(str(dev))

    return dev_dict


###########################################
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Display switcher for XRandR')
    parser.add_argument('action', metavar='action', choices=ACTIONS,
                        nargs='?', default='status',
                        help='action to be performed (one of {' +
                        ', '.join(ACTIONS) + '})')
    parser.add_argument('-v', '--verbose', help='increase verbosity level',
                        action='store_true')

    try:
        args = parser.parse_args()
    except Exception as ex:
        errprint(str(ex))

    if args.verbose:
        VERBOSE = 1

    xrandr_out = run_xrandr(['-d', ':0.0'])
    dev_dict = parse_xrandr(xrandr_out)
    print(str(dev_dict))

    dev_connected = [k for k, v in dev_dict.items() if v.status == 'connected']
    assert len(dev_connected) in {1, 2}

    # dev_primary = filter(lambda x, y: y.primary, dev_dict.items())
    dev_primary = [(k, v) for k, v in dev_dict.items() if v.primary]
    assert len(dev_primary) == 1
    primary_out = dev_primary[0][0]

    dev_active = [k for k, v in dev_dict.items() if v.active]
    assert len(dev_active) in {1, 2}

    secondary_out = ''
    if len(dev_connected) == 2:
        secondary_out = set(dev_connected) - {primary_out}
        assert len(secondary_out) == 1
        secondary_out = secondary_out.pop()

    if args.action == 'switch':
        if len(dev_connected) == 1:
            xrandr_turn_on(primary_out)
        elif len(dev_active) == 2:
            xrandr_turn_on(primary_out)
            xrandr_turn_off(secondary_out)
        elif dev_active == [primary_out]:
            xrandr_turn_off(primary_out)
            xrandr_turn_on(secondary_out)
        elif dev_active == [secondary_out]:
            xrandr_turn_on(primary_out)
            xrandr_turn_on(secondary_out, ['--right-of ' + primary_out])
        else:
            assert False
    else:
        assert args.action == 'status'

        # print(connected_lines)
        print('Connected devices:  ' + ' '.join(dev_connected))
        print('Active devices:     ' + ' '.join(dev_active))
        print('Primary output:     ' + primary_out)
        print('Secondary output:   ' + ('None' if not secondary_out else secondary_out))
